name: burc
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  package_info_plus: ^3.0.1
  animate_do: ^2.1.0
  page_transition: ^2.0.9
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  flutter_widget_from_html_core: ^0.9.0
  intl: ^0.17.0
  datetime_picker_formfield: ^2.0.1
  date_time_picker: ^2.1.0
  flutter_native_splash: ^2.2.0+1
  flutter_datetime_picker: ^1.5.1

  flutter_localizations:
    sdk: flutter
  google_fonts: ^3.0.1
  path_provider: ^2.0.11
  screenshot: ^1.2.3
  flutter_linear_datepicker: ^2.0.4
  flutter_holo_date_picker: ^1.1.0
  flutter_time_picker_spinner: ^2.0.0
  flutter_local_notifications: ^9.1.4
  rxdart: ^0.27.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_app_name: ^0.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/burc/
    - assets/elementler/
    - assets/gezegenler/

flutter_native_splash:
  background_image: assets/bg.png
  image: assets/icon.png
  # branding: assets/zodcom.png
  android_12:
    image: assets/icon.png
    background_image: assets/bg.png

#flutter pub run flutter_native_splash:create

flutter_app_name:
  name: "Yay Burcu"

flutter_icons:
  android: "logoicon"
  ios: true
  image_path: "assets/burc/yay.jpg"

  # flutter pub run change_app_package_name:main com.shemaster.yay
  # flutter pub run flutter_app_name
  # flutter pub run flutter_launcher_icons:main
  # flutterfire configure
  # flutter build appbundle --build-name=1.1.0 --build-number=1

  # sh1 alma
  # gradlew signingReport
  # keytool -list -v -keystore "C:\Users\yunus\.android\debug.keystore" -alias androiddebugkey -storepass android -keypass android

  #firebase
  #flutter pub add firebase_core
  #dart pub global activate flutterfire_cli
  #flutterfire configure
  #flutter run -v
#-------------------------
# flutter build apk --split-per-abi

#-------------------------
# flutter upgrade .
# dart migrate.
# flutter pub outdated --mode=null-safety
# flutter pub upgrade --null-safety
# dart migrate
