name: CI

on: push

# - run: flutter pub run change_app_package_name:main com.shemaster.akrep
# - run: flutter pub run flutter_app_name
# - run: flutter pub run flutter_launcher_icons:main
# - run: flutter pub run flutter_native_splash:create

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter format .
      - run: dart fix --dry-run
      - run: dart fix --apply
      # - run: flutter analyze
      # - run: flutter test

  # build_ios:
  #   name: Build Flutter (iOS)
  #   needs: [flutter_test]
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: "12.x"
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: "stable"
  #     - run: flutter pub get
  #     - run: flutter clean
  #     - run: flutter build ios --release --no-codesign

  # build_appbundle:
  #   name: Build Flutter (Android)
  #   needs: [flutter_test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: "12.x"
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         channel: "stable"
  #     - run: flutter pub get
  #     - run: flutter clean
  #     - run: flutter build appbundle
